# Generated by Django 4.1.2 on 2022-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_status',
            field=models.CharField(choices=[('yes, thank you!', 'Booked'), ('no', 'Not Booked')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
